# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hardwareinventory/msg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bhardwareinventory/msg.proto\x12 org.lfedge.eve.hardwareinventory\"+\n\x0cUSBBusDevnum\x12\x0b\n\x03\x62us\x18\x01 \x01(\x03\x12\x0e\n\x06\x64\x65vnum\x18\x02 \x01(\x03\"\xa4\x02\n\tUSBDevice\x12\x45\n\npci_parent\x18\x01 \x01(\x0b\x32,.org.lfedge.eve.hardwareinventory.PCIAddressH\x00\x88\x01\x01\x12G\n\nusb_parent\x18\x02 \x01(\x0b\x32..org.lfedge.eve.hardwareinventory.USBBusDevnumH\x01\x88\x01\x01\x12\x11\n\tvendor_id\x18\x03 \x01(\r\x12\x12\n\nproduct_id\x18\x04 \x01(\r\x12\x42\n\nbus_devnum\x18\x05 \x01(\x0b\x32..org.lfedge.eve.hardwareinventory.USBBusDevnumB\r\n\x0b_pci_parentB\r\n\x0b_usb_parent\";\n\nPCIAddress\x12\x0b\n\x03\x62us\x18\x01 \x01(\r\x12\x0e\n\x06\x64\x65vice\x18\x02 \x01(\r\x12\x10\n\x08\x66unction\x18\x03 \x01(\r\"\xaa\x02\n\tPCIDevice\x12&\n\x19parent_pci_device_address\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x0e\n\x06\x64river\x18\x02 \x01(\t\x12=\n\x07\x61\x64\x64ress\x18\x03 \x01(\x0b\x32,.org.lfedge.eve.hardwareinventory.PCIAddress\x12\x11\n\tvendor_id\x18\x04 \x01(\r\x12\x11\n\tdevice_id\x18\x05 \x01(\r\x12\x10\n\x08revision\x18\x06 \x01(\r\x12\x14\n\x0csubsystem_id\x18\x07 \x01(\r\x12\x10\n\x08\x63lass_id\x18\x08 \x01(\x04\x12\x13\n\x0bsubclass_id\x18\t \x01(\x04\x12\x13\n\x0biommu_group\x18\n \x01(\tB\x1c\n\x1a_parent_pci_device_address\"\xa7\x01\n\x0cInventoryMsg\x12\x13\n\x0b\x65ve_version\x18\x01 \x01(\t\x12@\n\x0bpci_devices\x18\x02 \x03(\x0b\x32+.org.lfedge.eve.hardwareinventory.PCIDevice\x12@\n\x0busb_devices\x18\x03 \x03(\x0b\x32+.org.lfedge.eve.hardwareinventory.USBDeviceBS\n org.lfedge.eve.hardwareinventoryZ/github.com/lf-edge/eve-api/go/hardwareinventoryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hardwareinventory.msg_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n org.lfedge.eve.hardwareinventoryZ/github.com/lf-edge/eve-api/go/hardwareinventory'
  _globals['_USBBUSDEVNUM']._serialized_start=65
  _globals['_USBBUSDEVNUM']._serialized_end=108
  _globals['_USBDEVICE']._serialized_start=111
  _globals['_USBDEVICE']._serialized_end=403
  _globals['_PCIADDRESS']._serialized_start=405
  _globals['_PCIADDRESS']._serialized_end=464
  _globals['_PCIDEVICE']._serialized_start=467
  _globals['_PCIDEVICE']._serialized_end=765
  _globals['_INVENTORYMSG']._serialized_start=768
  _globals['_INVENTORYMSG']._serialized_end=935
# @@protoc_insertion_point(module_scope)
