# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nestedappinstancemetrics/runtimestatus.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from info import common_pb2 as info_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,nestedappinstancemetrics/runtimestatus.proto\x12\'org.lfedge.eve.nestedappinstancemetrics\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x11info/common.proto\"\x87\x01\n\x10RuntimeErrorInfo\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\x08severity\x18\x03 \x01(\x0e\x32\x1d.org.lfedge.eve.info.Severity\"c\n\rRuntimeStatus\x12\n\n\x02id\x18\x01 \x01(\t\x12\x46\n\x03\x65rr\x18\x02 \x03(\x0b\x32\x39.org.lfedge.eve.nestedappinstancemetrics.RuntimeErrorInfoB8Z6github.com/lf-edge/eve-api/go/nestedappinstancemetricsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nestedappinstancemetrics.runtimestatus_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z6github.com/lf-edge/eve-api/go/nestedappinstancemetrics'
  _globals['_RUNTIMEERRORINFO']._serialized_start=142
  _globals['_RUNTIMEERRORINFO']._serialized_end=277
  _globals['_RUNTIMESTATUS']._serialized_start=279
  _globals['_RUNTIMESTATUS']._serialized_end=378
# @@protoc_insertion_point(module_scope)
