// Copyright(c) 2025 Zededa, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: nestedappinstancemetrics/runtimestatus.proto

package nestedappinstancemetrics

import (
	info "github.com/lf-edge/eve-api/go/info"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Errors in response to the application of configuration.
// Deliberately distinct from info.ErrorInfo: a runtime has no view of
// the device entities that info.ErrorInfo.entities/retry_condition
// describe. Only the Severity enum is shared with info.
type RuntimeErrorInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Timestamp   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                  // Timestamp at which error had occurred
	Severity    info.Severity          `protobuf:"varint,3,opt,name=severity,proto3,enum=org.lfedge.eve.info.Severity" json:"severity,omitempty"` // Severity of the error
}

func (x *RuntimeErrorInfo) Reset() {
	*x = RuntimeErrorInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nestedappinstancemetrics_runtimestatus_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuntimeErrorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeErrorInfo) ProtoMessage() {}

func (x *RuntimeErrorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_nestedappinstancemetrics_runtimestatus_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeErrorInfo.ProtoReflect.Descriptor instead.
func (*RuntimeErrorInfo) Descriptor() ([]byte, []int) {
	return file_nestedappinstancemetrics_runtimestatus_proto_rawDescGZIP(), []int{0}
}

func (x *RuntimeErrorInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RuntimeErrorInfo) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *RuntimeErrorInfo) GetSeverity() info.Severity {
	if x != nil {
		return x.Severity
	}
	return info.Severity(0)
}

// RuntimeStatus represents the status of a runtime on EVE-OS
// which may reside in an AppInstance.
// A single RuntimeStatus in protobuf form will be returned from
// GET /api/v1/runtime/status for every AppInstance where
// AppInstanceConfig.runtime_type!=APP_RUNTIME_TYPE_UNSPECIFIED
type RuntimeStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Id is the uuid of the runtime app instance
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Errors reported by a runtime when applying config eg. cloud-init
	Err []*RuntimeErrorInfo `protobuf:"bytes,2,rep,name=err,proto3" json:"err,omitempty"`
}

func (x *RuntimeStatus) Reset() {
	*x = RuntimeStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nestedappinstancemetrics_runtimestatus_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuntimeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeStatus) ProtoMessage() {}

func (x *RuntimeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_nestedappinstancemetrics_runtimestatus_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeStatus.ProtoReflect.Descriptor instead.
func (*RuntimeStatus) Descriptor() ([]byte, []int) {
	return file_nestedappinstancemetrics_runtimestatus_proto_rawDescGZIP(), []int{1}
}

func (x *RuntimeStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RuntimeStatus) GetErr() []*RuntimeErrorInfo {
	if x != nil {
		return x.Err
	}
	return nil
}

var File_nestedappinstancemetrics_runtimestatus_proto protoreflect.FileDescriptor

var file_nestedappinstancemetrics_runtimestatus_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2f, 0x72, 0x75, 0x6e, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x27,
	0x6f, 0x72, 0x67, 0x2e, 0x6c, 0x66, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x65, 0x76, 0x65, 0x2e, 0x6e,
	0x65, 0x73, 0x74, 0x65, 0x64, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x69, 0x6e, 0x66, 0x6f, 0x2f, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa9, 0x01, 0x0a, 0x10,
	0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x39, 0x0a, 0x08,
	0x73, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d,
	0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x6c, 0x66, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x65, 0x76, 0x65, 0x2e,
	0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x53, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x52, 0x08, 0x73,
	0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x22, 0x6c, 0x0a, 0x0d, 0x52, 0x75, 0x6e, 0x74, 0x69,
	0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x4b, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x39, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x6c, 0x66, 0x65, 0x64,
	0x67, 0x65, 0x2e, 0x65, 0x76, 0x65, 0x2e, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x61, 0x70, 0x70,
	0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2e,
	0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x03, 0x65, 0x72, 0x72, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x66, 0x2d, 0x65, 0x64, 0x67, 0x65, 0x2f, 0x65, 0x76, 0x65, 0x2d,
	0x61, 0x70, 0x69, 0x2f, 0x67, 0x6f, 0x2f, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x61, 0x70, 0x70,
	0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nestedappinstancemetrics_runtimestatus_proto_rawDescOnce sync.Once
	file_nestedappinstancemetrics_runtimestatus_proto_rawDescData = file_nestedappinstancemetrics_runtimestatus_proto_rawDesc
)

func file_nestedappinstancemetrics_runtimestatus_proto_rawDescGZIP() []byte {
	file_nestedappinstancemetrics_runtimestatus_proto_rawDescOnce.Do(func() {
		file_nestedappinstancemetrics_runtimestatus_proto_rawDescData = protoimpl.X.CompressGZIP(file_nestedappinstancemetrics_runtimestatus_proto_rawDescData)
	})
	return file_nestedappinstancemetrics_runtimestatus_proto_rawDescData
}

var file_nestedappinstancemetrics_runtimestatus_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_nestedappinstancemetrics_runtimestatus_proto_goTypes = []interface{}{
	(*RuntimeErrorInfo)(nil),      // 0: org.lfedge.eve.nestedappinstancemetrics.RuntimeErrorInfo
	(*RuntimeStatus)(nil),         // 1: org.lfedge.eve.nestedappinstancemetrics.RuntimeStatus
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(info.Severity)(0),            // 3: org.lfedge.eve.info.Severity
}
var file_nestedappinstancemetrics_runtimestatus_proto_depIdxs = []int32{
	2, // 0: org.lfedge.eve.nestedappinstancemetrics.RuntimeErrorInfo.timestamp:type_name -> google.protobuf.Timestamp
	3, // 1: org.lfedge.eve.nestedappinstancemetrics.RuntimeErrorInfo.severity:type_name -> org.lfedge.eve.info.Severity
	0, // 2: org.lfedge.eve.nestedappinstancemetrics.RuntimeStatus.err:type_name -> org.lfedge.eve.nestedappinstancemetrics.RuntimeErrorInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_nestedappinstancemetrics_runtimestatus_proto_init() }
func file_nestedappinstancemetrics_runtimestatus_proto_init() {
	if File_nestedappinstancemetrics_runtimestatus_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nestedappinstancemetrics_runtimestatus_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuntimeErrorInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nestedappinstancemetrics_runtimestatus_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuntimeStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nestedappinstancemetrics_runtimestatus_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nestedappinstancemetrics_runtimestatus_proto_goTypes,
		DependencyIndexes: file_nestedappinstancemetrics_runtimestatus_proto_depIdxs,
		MessageInfos:      file_nestedappinstancemetrics_runtimestatus_proto_msgTypes,
	}.Build()
	File_nestedappinstancemetrics_runtimestatus_proto = out.File
	file_nestedappinstancemetrics_runtimestatus_proto_rawDesc = nil
	file_nestedappinstancemetrics_runtimestatus_proto_goTypes = nil
	file_nestedappinstancemetrics_runtimestatus_proto_depIdxs = nil
}
