name: Build and Test
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  report:
    name: Report
    runs-on: ubuntu-latest
    steps:
      - name: ref
        run: echo ${{ github.ref }}
      - name: event_name
        run: echo ${{ github.event_name }}
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: arduino/setup-protoc@v2
        with:
          version: '21.9'
          repo-token: ${{ secrets.GITHUB_TOKEN }}          
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.20
      - name: install protodot
        run: go install github.com/seamia/protodot@v1.2.0
      - name: install protoc-gen-go
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1
      - name: make
        run: make proto
      - name: check no uncommitted files
        run: |
          # we run it twice, so that it will report on the logs
          echo "changed and uncommitted files"
          git status --short          
          if [ $(git status --short) != '' ]; then
            # print the diff so we can fix it, if there is an issue
            git diff
            exit 1
          fi
